name: nutrichild
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  shared_preferences: ^2.0.3
  table_calendar: ^3.0.9
  path: ^1.8.3
  fl_chart: ^0.65.0
  intl: ^0.20.1
  flutter_launcher_icons: ^0.14.3
  go_router: ^14.7.1
  dartz: ^0.10.1
  get_it: ^7.0.0
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 23

# For information on the generic Dart part of this file, see the
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 100
